apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - example-sno       # template only, not deployed
  # - example-3node     # template only, not deployed
  - edge-sno01
  - edge-bond-sno02
