apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance

metadata:
  name: edge-sno01
  namespace: edge-sno01

spec:
  clusterName: edge-sno01

  baseDomain: ocp.local

  pullSecretRef:
    name: assisted-deployment-pull-secret

  clusterImageSetNameRef: img4.22.11-x86-64-appsub

  templateRefs:
    - name: ai-cluster-templates-v1
      namespace: open-cluster-management

  sshPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEPFTI/XcJpZCzE4XTLM+8/9rYrTVF1bQ7kYqiK1+r4h root@hvm1"

  clusterType: SNO

  networkType: OVNKubernetes


  machineNetwork:
    - cidr: 172.28.0.0/24

  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23

  serviceNetwork:
    - cidr: 172.30.0.0/16

  nodes:
    - hostName: edge-sno01.ocp.local

      role: master

      templateRefs:
        - name: ai-node-templates-v1
          namespace: open-cluster-management

      bmcAddress: "redfish-virtualmedia+https://172.28.0.13/redfish/v1/Systems/1"

      bmcCredentialsName:
        name: edge-sno01-bmc-secret

      bootMACAddress: "e8:eb:d3:ee:70:a4"

      bootMode: UEFI

      nodeNetwork:
        interfaces:
          - name: eno1
            macAddress: "e8:eb:d3:ee:70:a4"

        config:
          interfaces:
            - name: eno1
              type: ethernet
              state: up

              ipv4:
                enabled: true
                dhcp: false
                address:
                  - ip: 172.28.0.42
                    prefix-length: 24

              ipv6:
                enabled: false

          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 172.28.0.1
                next-hop-interface: eno1

          dns-resolver:
            config:
              server:
                - 172.28.0.2

